### ISSUE TITLE
What to do to use your nix-config outside NixOS

### ISSUE THREAD

**Issue by cognivore** [donovanglover/nix-config#4]
# Why?

Many people use home-manager to get greatness of declarative configurations while retaining flexibility of doing dirty things to their systems.

# How?

 - [x] Please clarify which subset of your nix-config can be used with plain home-manager.
 - [x] If the answer is "none", but porting is possible, please give some hints about how to approach such porting.

Cheers :heart:

**Comment by donovanglover** [comment]
Hi all of my devices run NixOS and I don't use home-manager standalone.

Most of the home-manager stuff should work except parts that use `nixosConfig`, which you'd have to replace with your own thing.
